kind: pipeline
name: blog
steps:
  - name: build 
    image: plugins/hugo
    settings:
      config: ./config.toml           # The path to the configuration file
      output: ./public                # The output directory
  - name: publish 
    image: tencentcloudbase/cloudbase-framework-runner:latest
    command:
      - tcb login --apiKeyId $APPID --apiKey $APPKEY
      - tcb hosting:deploy ./public -e $ENV_ID
    environment:
      APPID:
        from_secret: APPID
      APPKEY:
        from_secret: APPKEY
      ENV_ID:
        from_secret: ENV_ID


